### ISSUE TITLE
Pls Update

### ISSUE THREAD

**Issue by Xingtaiduan** [renlua/crack#1]
The script named "云破解" doesn't work. 
![Uploading Screenshot_2024-08-12-16-10-09-82_080032403b0f3d7ce099ec68649d222a.jpg…]()
fix it

**Comment by Xingtaiduan** [comment]
![Uploading Screenshot_2024-08-12-16-10-09-82_080032403b0f3d7ce099ec68649d222a.jpg…]()

**Comment by Xingtaiduan** [comment]
![Uploading Screenshot_2024-08-12-16-10-09-82_080032403b0f3d7ce099ec68649d222a.jpg…]()

**Comment by Xingtaiduan** [comment]
😡

**Comment by renlua** [comment]
不是哥们，闲的啊，来github发Update ，还是英文的
